#!/usr/bin/env python3
"""Generate the sealed IANA TZDB local-midnight semantics artifact.

This is a build-time reproducibility tool only.  The Julia validator reads the
checked-in artifact and never consults the host timezone database.  Invoke it
with the exact IANA source archive named below; it verifies the archive's
SHA-256 before compiling the three allowlisted zones with ``zic``.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import os
import pathlib
import shutil
import subprocess
import sys
import tarfile
import tempfile
from zoneinfo import ZoneInfo


ARTIFACT_SCHEMA = "beforeit-us-timezone-semantics.v1"
ARTIFACT_ID = "beforeit-us-iana-tzdb-local-midnight-semantics.2026c.v1"
TZDB_VERSION = "2026c"
TZDB_URL = "https://data.iana.org/time-zones/releases/tzdata2026c.tar.gz"
TZDB_SHA256 = "e4a178a4477f3d0ea77cc31828ff72aa38feff8d61aa13e7e99e142e9d902be4"
EXPECTED_ARTIFACT_SHA256 = "8ed940e6deb1a1aa0922369eb8b0ad327ecf52def3c37c7317f81b87afe7a174"
START = dt.date(1997, 1, 1)
# The final entry is a boundary sentinel so evidence through 2035-12-31 can
# look up the offset at the following local midnight.
END = dt.date(2036, 1, 1)
ZONES = ("UTC", "America/New_York", "America/Chicago")


def sha256_file(path: pathlib.Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def safely_extract_source(archive: tarfile.TarFile, destination: pathlib.Path) -> None:
    """Extract only regular files/directories with relative, traversal-free names."""
    members = archive.getmembers()
    for member in members:
        posix_name = pathlib.PurePosixPath(member.name)
        windows_name = pathlib.PureWindowsPath(member.name)
        if (
            posix_name.is_absolute()
            or ".." in posix_name.parts
            or windows_name.drive
            or windows_name.root
            or ".." in windows_name.parts
        ):
            raise SystemExit(f"unsafe path in IANA source archive: {member.name!r}")
        if not (member.isfile() or member.isdir()):
            raise SystemExit(
                "IANA source archive contains an unsupported link or special "
                f"member: {member.name!r}"
            )
    archive.extractall(destination, members=members)


def canonical_write(value: object) -> bytes:
    if isinstance(value, dict):
        result = f"M{len(value)}{{".encode()
        for key in sorted(value):
            result += canonical_write(str(key)) + canonical_write(value[key])
        return result + b"}"
    if isinstance(value, (list, tuple)):
        return b"A" + str(len(value)).encode() + b"[" + b"".join(
            canonical_write(item) for item in value
        ) + b"]"
    if isinstance(value, str):
        encoded = value.encode("utf-8")
        return b"S" + str(len(encoded)).encode() + b":" + encoded
    raise TypeError(f"unsupported canonical value: {type(value)!r}")


def canonical_sha256(value: dict) -> str:
    value = dict(value)
    artifact = dict(value["artifact"])
    artifact.pop("content_sha256", None)
    value["artifact"] = artifact
    return hashlib.sha256(canonical_write(value)).hexdigest()


def offset_string(offset: dt.timedelta) -> str:
    minutes = int(offset.total_seconds() // 60)
    sign = "+" if minutes >= 0 else "-"
    minutes = abs(minutes)
    return f"{sign}{minutes // 60:02d}:{minutes % 60:02d}"


def zone_segments(zone_path: pathlib.Path) -> list[dict[str, str]]:
    with zone_path.open("rb") as handle:
        zone = ZoneInfo.from_file(handle)
    segments: list[dict[str, str]] = []
    current = START
    previous_offset: str | None = None
    while current <= END:
        offset = offset_string(dt.datetime.combine(current, dt.time()).replace(tzinfo=zone).utcoffset())
        if offset != previous_offset:
            segments.append({"local_date_start": current.isoformat(), "utc_offset": offset})
            previous_offset = offset
        current += dt.timedelta(days=1)
    return segments


def toml_quote(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_artifact(artifact: dict) -> str:
    header = artifact["artifact"]
    source = artifact["source"]
    coverage = artifact["coverage"]
    lines = ["# Generated by generate_timezone_semantics.py; do not edit by hand.", "[artifact]"]
    for key in ("schema_version", "artifact_id", "canonicalization", "digest_algorithm", "content_sha256"):
        lines.append(f"{key} = {toml_quote(header[key])}")
    lines.extend(["", "[source]"])
    for key in ("iana_tzdb_version", "iana_tzdb_source_url", "iana_tzdb_source_sha256", "generation_method"):
        lines.append(f"{key} = {toml_quote(source[key])}")
    lines.extend(["", "[coverage]"])
    for key in ("local_date_start_inclusive", "local_date_end_inclusive", "local_midnight_semantics"):
        lines.append(f"{key} = {toml_quote(coverage[key])}")
    for zone in ZONES:
        lines.extend(["", f"[zones.{toml_quote(zone)}]"])
        for segment in artifact["zones"][zone]["segments"]:
            lines.append("[[zones." + toml_quote(zone) + ".segments]]")
            lines.append(f"local_date_start = {toml_quote(segment['local_date_start'])}")
            lines.append(f"utc_offset = {toml_quote(segment['utc_offset'])}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("source_archive", type=pathlib.Path)
    parser.add_argument("output", type=pathlib.Path)
    arguments = parser.parse_args()
    if sha256_file(arguments.source_archive) != TZDB_SHA256:
        raise SystemExit("source archive SHA-256 does not match IANA tzdata2026c")
    if shutil.which("zic") is None:
        raise SystemExit("zic is required to compile the pinned IANA source")
    with tempfile.TemporaryDirectory() as temporary:
        root = pathlib.Path(temporary)
        with tarfile.open(arguments.source_archive, "r:gz") as archive:
            safely_extract_source(archive, root)
        zoneinfo = root / "zoneinfo"
        subprocess.run(
            ["zic", "-d", os.fspath(zoneinfo), os.fspath(root / "etcetera"), os.fspath(root / "northamerica")],
            check=True,
        )
        artifact = {
            "artifact": {
                "schema_version": ARTIFACT_SCHEMA,
                "artifact_id": ARTIFACT_ID,
                "canonicalization": "utf8-length-prefixed-sorted-map-array-order.v1",
                "digest_algorithm": "sha256",
                "content_sha256": "",
            },
            "source": {
                "iana_tzdb_version": TZDB_VERSION,
                "iana_tzdb_source_url": TZDB_URL,
                "iana_tzdb_source_sha256": TZDB_SHA256,
                "generation_method": "zic-compiled-iana-source-plus-python-zoneinfo-local-midnight-scan.v1",
            },
            "coverage": {
                "local_date_start_inclusive": START.isoformat(),
                "local_date_end_inclusive": END.isoformat(),
                "local_midnight_semantics": "offset_at_source_local_midnight",
            },
            "zones": {
                "UTC": {
                    "segments": [
                        {
                            "local_date_start": START.isoformat(),
                            "utc_offset": "+00:00",
                        },
                    ],
                },
                **{
                    zone: {"segments": zone_segments(zoneinfo / zone)}
                    for zone in ZONES
                    if zone != "UTC"
                },
            },
        }
        generated_hash = canonical_sha256(artifact)
        if generated_hash != EXPECTED_ARTIFACT_SHA256:
            raise SystemExit(
                "generated timezone semantics do not match the sealed "
                f"artifact: expected {EXPECTED_ARTIFACT_SHA256}, got "
                f"{generated_hash}"
            )
        artifact["artifact"]["content_sha256"] = generated_hash
        arguments.output.write_text(render_artifact(artifact), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
